Sequence:
    - Combo:
        Text:
            - "Curbfeeler"
            - ""
            - "Presents"
        Font: large
        Animation: starsgif
        lampshow: attract_show_1
        duration: 3.0
    - Combo:
        Text:
            - ""
            - ""
            - ""
        Font: large
        Animation: starsgif
        lampshow: attract_show_1
        duration: 2.0
    - Combo:
        Text:
            - "Pin*Bot 2.0"
            - ""
            - "PROC Edition"
        Font: large
        Animation: starsgif
        FontStyle: blueish
        lampshow: attract_show_2
        duration: 4.0
    - HighScores:
        Font: large
        Animation: starsgif
        Order:
            - player
            - category
            - score
        duration: 1.0